### PR TITLE
Target RxSwift 3

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by inamiy** [comment]
Can you `carthage update` to update `Cartfile.resolved` and git-submodules?

**Comment by AndrewSB** [comment]
yes! I just realized that was a problem 😄 

`carthage update --use-submodules`, right?

**Comment by AndrewSB** [comment]
any reason we're using submodules instead of just using the built frameworks?

**Comment by inamiy** [comment]
Carthage is used only for dependency resolution so that non-Carthage users can also pull the dependencies via git-submodules.
(And I often tweak their source codes whenever necessary rather than using pre-built frameworks)

Yes, just calling `carthage update --use-submodules` (or option may not even be needed?) will be fine 😄

**Comment by AndrewSB** [comment]
done 😄

**Comment by inamiy** [comment]
Hmm... CI failed and there are quite a lot of breaking changes from RxSwift 3.0 beta.1 to release version.
https://github.com/ReactiveX/RxSwift/blob/master/CHANGELOG.md

Will you try fixing this?
Or, I can continue working from your commits later 😌

**Comment by AndrewSB** [comment]
I can commit tomorrow morning (in ~11 hours) 😄 

Thank you for the invite!

**Comment by AndrewSB** [comment]
@inamiy this looks good to me, give it a once over and merge if you feel the same?

**Comment by inamiy** [comment]
@AndrewSB Awesome! Thanks for your work 😄

**Pull request merged**
